version: '3.8'

services:
  # SERVIÇO DO BANCO DE DADOS POSTGRESQL
  database:
    image: postgres:15-alpine
    container_name: postgres_desafio
    restart: always

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # SERVIÇO DA APLICAÇÃO
  web:
    build: .
    container_name: flask_desafio
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      # Isso sobrescreve a variável do .env!
      DB_HOST: database

volumes:
  postgres_data: